-- Question:
-- Among sufficiently active users, how are strict, neutral, and generous rating behaviors distributed relative 
-- to the platform-wide average, and how much rating activity does each behavioral group represent?

-- Purpose:
-- To identify meaningful differences in users’ rating tendencies after accounting for their activity levels,
-- classify sufficiently active users as strict, neutral, or generous relative to the platform-wide average,
-- and measure how users and rating activity are distributed across these behavioral groups.


-- The minimum activity threshold was based on the user activity segmentation 
-- developed in the previous analysis. Users with at least 51 ratings were retained 
-- to reduce the influence of averages based on relatively limited activity.

-- Exploratory Analysis: Distribution of User Average Ratings
WITH quartileCTE AS (
        SELECT 
            userId, 
            COUNT(*) AS total_ratings,
            AVG(rating) AS avg_rating,
            NTILE(4) OVER(
                ORDER BY AVG(rating)
            ) AS avg_segment,

            (SELECT AVG(rating)
            FROM ratings) AS platform_wide_avg_rating
            
        FROM ratings
        GROUP BY userId
        HAVING COUNT(*) >= 51
)

SELECT 
    avg_segment,
    ROUND(MIN(avg_rating), 2) AS min_user_avg,
    ROUND(MAX(avg_rating), 2) AS max_user_avg,
    ROUND(AVG(avg_rating), 2) AS mean_user_avg,
    COUNT(*) AS total_users,
    ROUND(MAX(platform_wide_avg_rating), 2) AS platform_wide_avg_rating

FROM quartileCTE
GROUP BY avg_segment
;


-- Users whose average ratings were within ±0.25 of the platform-wide average were classified as 
-- neutral, preventing minor deviations from being interpreted as meaningful rating tendencies.
-- The ±0.25 neutral band is an analytical threshold selected to avoid overinterpreting minor differences.

-- Final Analysis: User Rating Behavior and Activity Contribution
WITH userMetricsCTE AS (
    SELECT 
            userId, 
            COUNT(*) AS total_ratings,
            AVG(rating) AS avg_rating,

            (SELECT AVG(rating)
            FROM ratings) AS platform_wide_avg_rating
            
        FROM ratings
        GROUP BY userId
        HAVING COUNT(*) >= 51
),

behaviorCTE AS (
    SELECT 
        userId,
        total_ratings,
        avg_rating,
        avg_rating - platform_wide_avg_rating AS deviation_from_mean,
        ABS(avg_rating - platform_wide_avg_rating) AS abs_deviation_from_mean,

        CASE
            WHEN ABS(avg_rating - platform_wide_avg_rating) <= 0.25
                THEN 'Neutral'
            WHEN avg_rating < platform_wide_avg_rating
                THEN 'Strict'
            ELSE 'Generous'
        END AS rating_behavior

    FROM userMetricsCTE
)

SELECT 
    rating_behavior,
    COUNT(*) AS total_users,
    ROUND(COUNT(*) * 100.0 /
          SUM(COUNT(*)) OVER(), 2) AS user_share_pct,

    SUM(total_ratings) AS total_ratings_generated,

    ROUND(SUM(total_ratings) * 100.0 /
          SUM(SUM(total_ratings)) OVER(), 2) AS rating_share_pct,

    ROUND(AVG(avg_rating), 2) AS avg_user_rating,
    
    ROUND(AVG(abs_deviation_from_mean), 2) AS avg_absolute_deviation

FROM behaviorCTE
GROUP BY rating_behavior
;


-- avg_user_rating is the unweighted mean of user-level averages,
-- so each eligible user contributes equally regardless of rating count.

-- User shares are calculated among users with at least 51 ratings.
-- Rating shares are calculated from ratings generated by these eligible users,
-- rather than from all ratings on the platform.
-- The platform-wide average is calculated across all rating records, so each individual rating contributes equally.